### ISSUE TITLE
`test_all_points` is failing

### ISSUE THREAD

**Issue by WillowP** [karina-klinkeviciute/rainbow-challenge#138]
This assertion is failing:

```py
assert user1.all_points == joined_challenge1.challenge.points + joined_challenge2.challenge.points
```

`user1.all_points` has a value of `0`.

After a bit of digging I found that this if statement seems to be validating and resulting in a `0` return: https://github.com/karina-klinkeviciute/rainbow-challenge/blob/main/rainbow/user/models.py#L204

**Comment by karina-klinkeviciute** [comment]
It was because in the code, I changed that the joined challenge counts towards the points only after it's status becomes "confirmed" but I haven't changed that in tests. I updated tests now.
